services:
  prometheus:
    image: 
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - 
    environment:
      - 
    command:
      - 
    
  grafana:
    image: 
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - 
    environment:
      - 
    command:
      - 

  zipkin:
    image: 
    container_name: zipkin
    ports:
      - 9411:9411
    volumes:
      - 
    environment:
      - 
    command:
      - 
