server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: job
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_service_name']
        target_label: service
      - source_labels: ['__meta_docker_container_label_com_docker_stack_namespace']
        target_label: stack
      - source_labels: ['__meta_docker_container_label_io_kubernetes_pod_name']
        target_label: pod
    pipeline_stages:
      - docker: {}
      - multiline:
          firstline: '^{'
          max_wait_time: 3s
